### ISSUE TITLE
System.json version not updated

### ISSUE THREAD

**Issue by drewg13** [jbhaywood/foundryvtt-honeyheist#4]
I see that you made a 1.2 update, but you didn't update the version field in your system.json.  I *think* this means that current installs won't see that there's an update available, but new installs will get the updated files.  Also, I would recommend updating your compatibleCoreVersion field to reflect the 0.8.x compatibility.  I tested it on 0.8.7, but you could probably bump it to 0.8.8 without issue.  I *think* if you make those updates to the system.json, delete the 1.2 release and tag, and recreate the 1.2 release, it should work going forward, but I've never been in that precise situation.

**Comment by jbhaywood** [comment]
Done. I do this like once a year so I'm not surprised I messed something up. Thanks for pointing it out.

**Comment by drewg13** [comment]
No problem, I really appreciate that you put this together.  My players needed something light, simple, and silly last weekend, because one of them was ill and we can only play remotely, so this was perfect.  They had a ridiculous time.
Something still isn't right, but I'm not sure what it is.  Foundry still somehow thinks it's version 1.1 and says there's an upgrade to 1.2 over and over.  The code's correct and working though.  Perhaps you need to add the 1.2 release to the FoundryVTT admin page?  Or it doesn't like putting 0.8.x in the compatibleCoreVersion field?  I'm relatively new to Foundry myself and programming in general, but I jumped on the 0.8.0 update early and have been trying to hang on ever since.

**Comment by drewg13** [comment]
I'll bet it's both.  I think in the new versions, if there's conflict between system versions and compatible Foundry versions on the Foundry website versus the included system manifest, it tries to work it out.  I'll bet the x in the compatibleCoreVersion is confusing it, so it's reverting to the information it has on the Foundry admin page for the package.  It's intended so you can update compatibility with new Foundry versions without having to make a new release just by updating the info on their website.

**Comment by jbhaywood** [comment]
Ok, after a bunch of creating new releases and updating all the things, I think it works now. Give it a shot and let me know. It should update to v1.21.

**Comment by drewg13** [comment]
Works great now!
